# Simple workflow for deploying static content to GitHub Pages
name: CI

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Enable Corepack
        run: corepack enable
      - name: Prepare Yarn
        run: corepack prepare yarn@4.5.1 --activate
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
